### ISSUE TITLE
Could no pass event EntityShootBowEvent

### ISSUE THREAD

**Issue by blackshot** [Indyuce/moar-bows#3]
i'm running PaperSpigot 1.15.1

`27.12 22:38:26 [Server] ERROR Could not pass event EntityShootBowEvent to MoarBows v2.5.1
27.12 22:38:26 [Server] INFO java.lang.NullPointerException: null
27.12 22:38:26 [Server] INFO at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770) ~[patched_1.15.1.jar:git-Paper-27]
27.12 22:38:26 [Server] INFO at com.sk89q.worldguard.protection.FlagValueCalculator.queryAllValues(FlagValueCalculator.java:268) ~[?:?]
27.12 22:38:26 [Server] INFO at com.sk89q.worldguard.protection.FlagValueCalculator.queryValue(FlagValueCalculator.java:223) ~[?:?]
27.12 22:38:26 [Server] INFO at com.sk89q.worldguard.protection.RegionResultSet.queryValue(RegionResultSet.java:103) ~[?:?]
27.12 22:38:26 [Server] INFO at net.Indyuce.moarbows.comp.worldguard.WorldGuardOn.isFlagAllowed(WorldGuardOn.java:49) ~[?:?]
27.12 22:38:26 [Server] INFO at net.Indyuce.moarbows.listener.ShootBow.a(ShootBow.java:54) ~[?:?]
27.12 22:38:26 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor523.execute(Unknown Source) ~[?:?]
27.12 22:38:26 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.1.jar:git-Paper-27]
27.12 22:38:26 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.1.jar:git-Paper-27]
27.12 22:38:26 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.1.jar:git-Paper-27]
27.12 22:38:26 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.15.1.jar:git-Paper-27]
27.12 22:38:26 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEntityShootBowEvent(CraftEventFactory.java:497) ~[patched_1.15.1.jar:git-Paper-27]
27.12 22:38:26 [Server] INFO at net.minecraft.server.v1_15_R1.ItemBow.a(ItemBow.java:65) ~[patched_1.15.1.jar:git-Paper-27]
27.12 22:38:26 [Server] INFO at net.minecraft.server.v1_15_R1.ItemStack.a(ItemStack.java:563) ~[patched_1.15.1.jar:git-Paper-27]
27.12 22:38:26 [Server] INFO at net.minecraft.server.v1_15_R1.EntityLiving.clearActiveItem(EntityLiving.java:3034) ~[patched_1.15.1.jar:git-Paper-27]
27.12 22:38:26 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1309) ~[patched_1.15.1.jar:git-Paper-27]
27.12 22:38:26 [Server] INFO at net.minecraft.server.v1_15_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.15.1.jar:git-Paper-27]
27.12 22:38:26 [Server] INFO at net.minecraft.server.v1_15_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.15.1.jar:git-Paper-27]
27.12 22:38:26 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.1.jar:git-Paper-27]
27.12 22:38:26 [Server] INFO at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.1.jar:git-Paper-27]
27.12 22:38:26 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.1.jar:git-Paper-27]
27.12 22:38:26 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.1.jar:git-Paper-27]
27.12 22:38:26 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.1.jar:git-Paper-27]
27.12 22:38:26 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.aZ(MinecraftServer.java:1037) ~[patched_1.15.1.jar:git-Paper-27]
27.12 22:38:26 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1030) ~[patched_1.15.1.jar:git-Paper-27]
27.12 22:38:26 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.1.jar:git-Paper-27]
27.12 22:38:26 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1014) ~[patched_1.15.1.jar:git-Paper-27]
27.12 22:38:26 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:937) ~[patched_1.15.1.jar:git-Paper-27]
27.12 22:38:26 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]`

**Comment by Indyuce** [comment]
Looks like an issue with WorldGuard. Make sure you're using the latest build available and double check your console for startup errors
