### ISSUE TITLE
Cannot craft the bows

### ISSUE THREAD

**Issue by fabi4s** [Indyuce/moar-bows#5]
Your plugin is amazing and fits exactly what I'm looking for though one slight issue is that the bows remain uncraftable regardless of what I change in the configs. Current setup is a vanilla spigot 1.15.2 with the plugin isolated. Everything except the crafting recipes function.

config.yml setting
disable-bow-craftings: false

bows.yml settings
craft-enabled: true

**Comment by assersson** [comment]
Same problem here

**Comment by Indyuce** [comment]
Should be fixed in the latest dev build
